\input texinfo.tex
@c %**start of header
@setfilename vicare-openssl.info
@settitle Openssl for Vicare
@c %**end of header

@include version.texi
@include macros.texi

@c page
@c ------------------------------------------------------------
@c Values.
@c ------------------------------------------------------------

@set TITLE                      Openssl for Vicare

@c To be used as @value{PACKAGE} whenever we need to include the full
@c name of this package.
@set PACKAGE                    Vicare/@openssl{}

@c To be used as @value{PACKAGE} whenever we need to include the
@c nickname of the project: the name that is used to compose the
@c distribution tarball or the web address.
@set PACKAGE_NICKNAME           vicare-openssl

@c To be used as @value{AUTHOR} whenever we need to include the list of
@c authors of this document.
@set AUTHOR                     Marco Maggi

@c To be used as @value{AUTHOR_EMAIL} whenever we need to include the
@c email of the *single* author of this document.
@set AUTHOR_EMAIL               @email{marco.maggi.ipsu@@poste.it}

@c To be used as @value{COPYRIGHT_YEARS} whenever we need to include the
@c list of copyright years.
@set COPYRIGHT_YEARS            2013

@c ------------------------------------------------------------

@set FOREIGN_PACKAGE            @openssl{}
@set FOREIGN_VERSION            1.0.1e
@set FOREIGN_URL                @url{http://www.openssl.org/}
@set FOREIGN_SCHEME_LIB         @library{vicare crypto openssl}
@set GITHUB_URL                 @url{http://github.com/marcomaggi/vicare-openssl}
@set DOWNLOAD_URL               @url{http://code.google.com/p/vicare-scheme/downloads/list}
@set DOCUMENTATION_URL          @url{http://marcomaggi.github.com/docs/vicare-openssl.html}


@macro opensslref{NODE, TITLE}
@xref{\NODE\,\TITLE\,\TITLE\,openssl}
@end macro

@macro openssl{}
@acronym{OpenSSL}
@end macro

@c page
@c ------------------------------------------------------------
@c Copyright notice.
@c ------------------------------------------------------------

@copying
This document describes version @version{} of @value{PACKAGE}, a
distribution of C and Scheme libraries for Vicare Scheme, an @rnrs{6}
compliant Scheme implementation; it provides bindings for the
@value{FOREIGN_PACKAGE} C language library.

The package is distributed under the terms of the @gnu{} General Public
License (@gpl{}) and can be downloaded from:

@center @value{DOWNLOAD_URL}

@noindent
development takes place at:

@center @value{GITHUB_URL}

@noindent
@value{FOREIGN_PACKAGE} is available at:

@center @value{FOREIGN_URL}

@noindent
Copyright @copyright{} @value{COPYRIGHT_YEARS} by @value{AUTHOR} @value{AUTHOR_EMAIL}

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the @gnu{} Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with
Invariant Sections being ``@gnu{} Free Documentation License'' and
``@gnu{} General Public License'', no Front--Cover Texts, and no
Back--Cover Texts.  A copy of the license is included in the section
entitled ``@gnu{} Free Documentation License''.
@end quotation
@end copying

@c page
@c ------------------------------------------------------------
@c Headers.
@c ------------------------------------------------------------

@titlepage
@title @value{TITLE}
@subtitle Revision @version{}
@author @value{AUTHOR} @value{AUTHOR_EMAIL}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ------------------------------------------------------------

@ifinfo
@dircategory Development
@direntry
* vicare-openssl: (vicare-openssl). @value{TITLE}.
@end direntry
@end ifinfo

@c ------------------------------------------------------------

@ignore
@syncodeindex tp cp
@syncodeindex vr cp
@syncodeindex fn cp
@end ignore

@c page
@ifnottex
@node Top
@top @value{TITLE}

@insertcopying

@menu
* overview::                    Overview of the package.
* version::                     Openssl version informations.
* plain::                       Plain programming interface.

Appendices

* Package License::             GNU General Public License.
* Documentation License::       GNU Free Documentation License.
* references::                  Bibliography and references.

Indexes

* concept index::               An entry for each concept.
* function index::              An entry for each function.
* variable index::              An entry for each variable.
* type index::                  An entry for each type.
@end menu
@end ifnottex

@c page
@node overview
@chapter Overview of the package


Vicare Scheme is an @rnrs{6} compliant Scheme language implementation in
the form of a native compiler for x86 architectures, officially
supporting @gnu{}+Linux systems.  @value{PACKAGE} is a distribution of C
language and Scheme language libraries for Vicare Scheme; it provides
bindings for the @value{FOREIGN_PACKAGE} C language library.

The last time the author bothered to update this paragraph, he had
tested @value{FOREIGN_PACKAGE} version @value{FOREIGN_VERSION}; This
product includes software developed by the OpenSSL Project for use in
the OpenSSL Toolkit.  (@url{http://www.openssl.org/})

The package installs a C language library implementing wrapper C
functions for the C language @value{FOREIGN_PACKAGE} library; on top of
this, the Scheme library @library{vicare crypto openssl} exports one
binding for some @value{FOREIGN_PACKAGE} public functions; additionally
the library @library{vicare crypto openssl constants} exports one
binding for some constant values defined in the C language header
@file{openssl/ssl.h} and others.

The following Scheme libraries are installed:

@table @library
@item vicare crypto openssl
@cindex Library @library{vicare crypto openssl}
@cindex @library{vicare crypto openssl}, library
It exports bindings for some @value{FOREIGN_PACKAGE} public functions.
All the Scheme function names are directly derived from the C function
names by replacing upper case with lower case and underscore characters
@samp{_} with dash characters @samp{-}; so @cfunc{SSL_library_init}
becomes @func{ssl-library-init}.

@item vicare crypto openssl unsafe-capi
@cindex Library @library{vicare crypto openssl unsafe-capi}
@cindex @library{vicare crypto openssl unsafe-capi}, library
It exports syntax bindings for some @value{FOREIGN_PACKAGE} public
functions.  All the Scheme syntax names are directly derived from the C
function names by replacing upper case with lower case and underscore
characters @samp{_} with dash characters @samp{-}; so
@cfunc{SSL_library_init} becomes @func{ssl-library-init}.

These syntaxes expand to a direct call to the C language wrapper
functions in the @value{PACKAGE} library; they are not meant to be
called in normal usage of the package.

@item vicare crypto openssl constants
@cindex Library @library{vicare crypto openssl constants}
@cindex @library{vicare crypto openssl constants}, library
It exports bindings for some constant values defined in the C language
header @file{openssl/ssl.h} and others.

@item vicare crypto openssl features
@cindex Library @library{vicare crypto openssl features}
@cindex @library{vicare crypto openssl features}, library
It exports one identifier syntax binding for each @code{HAVE_} constant
defined by the @command{configure} script, expanding to @true{} or
@false{}.
@end table

Scheme libraries are installed under the directory:

@center @file{$(libdir)/vicare-scheme}

After installation, under the directory:

@center @file{$(libexecdir)/@value{PACKAGE_NICKNAME}}

@noindent
a script @file{compile-all.sps} can be executed to precompile the
installed libraries; for example:

@example
$ sudo vicare \
   --fasl-directory /var/cache/vicare-scheme \
   --compile-dependencies \
      /usr/local/libexec/vicare-openssl/compile-all.sps
@end example

This document contains only a brief description of the functions: refer
to the @value{FOREIGN_PACKAGE}'s documentation for details.

@c page
@node version
@chapter @value{FOREIGN_PACKAGE} version informations


The installed C library follows version numbering as established by the
@gnu{} Autotools.  For an explanation of interface numbers as managed by
@gnu{} Libtool @xref{Libtool versioning, interface, Libtool's versioning
system, libtool, Shared library support for @gnu{}}.

The following bindings are exported by the library
@value{FOREIGN_SCHEME_LIB}.


@defun vicare-openssl-version-interface-current
@defunx vicare-openssl-version-interface-revision
@defunx vicare-openssl-version-interface-age
Return a fixnum representing a version number.
@end defun


@defun vicare-openssl-version
Return a Scheme string representing the version number.
@end defun

@c page
@node plain
@chapter Plain programming interface


@menu
* plain init::                  Global initialisation functions.
* plain hash::                  Computing hash checksums.
* plain hmac::                  Computing message authentication codes.
* plain crypto::                Low-level cryptographic algorithms.
* plain evp::                   High-level cryptographic functions.
@end menu

@c page
@node plain init
@section Global initialisation functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun ssl-library-init
Initialise the library; return unspecified values.
@end defun

@c page
@node plain hash
@section Computing hash checksums


@menu
* plain hash md4::              Computing MD4 hash checksums.
* plain hash md5::              Computing MD5 hash checksums.
* plain hash mdc2::             Computing MDC2 hash checksums.
* plain hash sha1::             Computing SHA1 hash checksums.
* plain hash sha224::           Computing SHA224 hash checksums.
* plain hash sha256::           Computing SHA256 hash checksums.
* plain hash sha384::           Computing SHA384 hash checksums.
* plain hash sha512::           Computing SHA512 hash checksums.
* plain hash ripemd160::        Computing RIPEMD160 hash checksums.
* plain hash whirlpool::        Computing WHIRLPOOL hash checksums.
@end menu

@c page
@node plain hash md4
@subsection Computing MD4 hash checksums


@menu
* plain hash md4 struct::       Hash checksum data structures.
* plain hash md4 api::          Context updating functions.
* plain hash md4 direct::       Directly computing hash checksums.
@end menu

@c page
@node plain hash md4 struct
@subsubsection Hash checksum data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} md4-ctx
@cindex @var{MD4} argument
@cindex Argument @var{MD4}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{MD4_CTX}; it references an MD4 hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{MD4}.

There are two categories of @code{md4-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{md4-ctx} instances returned by @func{md4-init} do own the context.
When instances of this category are garbage collected or when
@func{md5-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun md4-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{md4-ctx}; otherwise
return @false{}.
@end defun


@defun md4-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{md4-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun md4-ctx-custom-destructor @var{MD4}
@defunx set-md4-ctx-custom-destructor! @var{MD4} @var{func}
Retrieve or set a destructor function associated to the @var{MD4}.

Whenever the @var{MD4} is closed, either explicitly with
@func{md4-final} or implicitly by the garbage collector, @var{func} is
applied to @var{MD4} before the internal state of @var{MD4} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{MD4}; if we do:

@example
(define context ...)
(set-md4-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((md4-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{MD4}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} md4-ctx @var{obj}
@deffnx {Validation Clause} false-or-md4-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{md4-ctx?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} md4-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-md4-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{md4-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hash md4 api
@subsubsection Context updating functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun md4-init
Allocate and initialise a new instance of @code{md4-ctx}; if successful
return the struct, else return @false{}.  @manpage{MD4_Init, MD4_Init}
@end defun


@defun md4-final @var{MD4}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  @manpage{MD4_Final,
MD4_Final}.  It is fine to apply this function multiple times to the
same @var{MD4} argument.
@end defun


@defun md4-update @var{MD4} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{MD4_Update, MD4_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash md4 direct
@subsubsection Directly computing hash checksums


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun md4 @var{input}
@defunx md4 @var{input} @var{input.len}
Perform a one--step checksum computing; return a bytevector holding the
result.  @manpage{MD4, MD4}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash md5
@subsection Computing MD5 hash checksums


@menu
* plain hash md5 struct::       Hash checksum data structures.
* plain hash md5 api::          Context updating functions.
* plain hash md5 direct::       Directly computing hash checksums.
@end menu

@c page
@node plain hash md5 struct
@subsubsection Hash checksum data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} md5-ctx
@cindex @var{MD5} argument
@cindex Argument @var{MD5}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{MD5_CTX}; it references an MD5 hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{MD5}.

There are two categories of @code{md5-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{md5-ctx} instances returned by @func{md5-init} do own the context.
When instances of this category are garbage collected or when
@func{md5-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun md5-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{md5-ctx}; otherwise
return @false{}.
@end defun


@defun md5-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{md5-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun md5-ctx-custom-destructor @var{MD5}
@defunx set-md5-ctx-custom-destructor! @var{MD5} @var{func}
Retrieve or set a destructor function associated to the @var{MD5}.

Whenever the @var{MD5} is closed, either explicitly with
@func{md5-final} or implicitly by the garbage collector, @var{func} is
applied to @var{MD5} before the internal state of @var{MD5} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{MD5}; if we do:

@example
(define context ...)
(set-md5-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((md5-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{MD5}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} md5-ctx @var{obj}
@deffnx {Validation Clause} false-or-md5-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{md5-ctx?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} md5-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-md5-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{md5-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hash md5 api
@subsubsection Context updating functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun md5-init
Allocate and initialise a new instance of @code{md5-ctx}; if successful
return the struct, else return @false{}.  @manpage{MD5_Init, MD5_Init}
@end defun


@defun md5-final @var{MD5}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  @manpage{MD5_Final,
MD5_Final}.  It is fine to apply this function multiple times to the
same @var{MD5} argument.
@end defun


@defun md5-update @var{MD5} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{MD5_Update, MD5_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash md5 direct
@subsubsection Directly computing hash checksums


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun md5 @var{input}
@defunx md5 @var{input} @var{input.len}
Perform a one--step checksum computing; return a bytevector holding the
result.  @manpage{MD5, MD5}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash mdc2
@subsection Computing MDC2 hash checksums


@menu
* plain hash mdc2 struct::       Hash checksum data structures.
* plain hash mdc2 api::          Context updating functions.
* plain hash mdc2 direct::       Directly computing hash checksums.
@end menu

@c page
@node plain hash mdc2 struct
@subsubsection Hash checksum data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} mdc2-ctx
@cindex @var{MDC2} argument
@cindex Argument @var{MDC2}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{MDC2_CTX}; it references an MDC2 hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{MDC2}.

There are two categories of @code{mdc2-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{mdc2-ctx} instances returned by @func{mdc2-init} do own the context.
When instances of this category are garbage collected or when
@func{mdc2-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun mdc2-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{mdc2-ctx}; otherwise
return @false{}.
@end defun


@defun mdc2-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{mdc2-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun mdc2-ctx-custom-destructor @var{MDC2}
@defunx set-mdc2-ctx-custom-destructor! @var{MDC2} @var{func}
Retrieve or set a destructor function associated to the @var{MDC2}.

Whenever the @var{MDC2} is closed, either explicitly with
@func{mdc2-final} or implicitly by the garbage collector, @var{func} is
applied to @var{MDC2} before the internal state of @var{MDC2} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{MDC2}; if we do:

@example
(define context ...)
(set-mdc2-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((mdc2-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{MDC2}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} mdc2-ctx @var{obj}
@deffnx {Validation Clause} false-or-mdc2-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{mdc2-ctx?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} mdc2-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-mdc2-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{mdc2-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hash mdc2 api
@subsubsection Context updating functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun mdc2-init
Allocate and initialise a new instance of @code{mdc2-ctx}; if successful
return the struct, else return @false{}.  @manpage{MDC2_Init, MDC2_Init}
@end defun


@defun mdc2-final @var{MDC2}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  @manpage{MDC2_Final,
MDC2_Final}.  It is fine to apply this function multiple times to the
same @var{MDC2} argument.
@end defun


@defun mdc2-update @var{MDC2} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{MDC2_Update, MDC2_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash mdc2 direct
@subsubsection Directly computing hash checksums


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun mdc2 @var{input}
@defunx mdc2 @var{input} @var{input.len}
Perform a one--step checksum computing; return a bytevector holding the
result.  @manpage{MDC2, MDC2}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash sha1
@subsection Computing SHA1 hash checksums


@menu
* plain hash sha1 struct::       Hash checksum data structures.
* plain hash sha1 api::          Context updating functions.
* plain hash sha1 direct::       Directly computing hash checksums.
@end menu

@c page
@node plain hash sha1 struct
@subsubsection Hash checksum data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} sha1-ctx
@cindex @var{SHA1} argument
@cindex Argument @var{SHA1}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{SHA1_CTX}; it references an SHA1 hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{SHA1}.

There are two categories of @code{sha1-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{sha1-ctx} instances returned by @func{sha1-init} do own the context.
When instances of this category are garbage collected or when
@func{md5-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun sha1-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{sha1-ctx}; otherwise
return @false{}.
@end defun


@defun sha1-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{sha1-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun sha1-ctx-custom-destructor @var{SHA1}
@defunx set-sha1-ctx-custom-destructor! @var{SHA1} @var{func}
Retrieve or set a destructor function associated to the @var{SHA1}.

Whenever the @var{SHA1} is closed, either explicitly with
@func{sha1-final} or implicitly by the garbage collector, @var{func} is
applied to @var{SHA1} before the internal state of @var{SHA1} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{SHA1}; if we do:

@example
(define context ...)
(set-sha1-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((sha1-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{SHA1}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} sha1-ctx @var{obj}
@deffnx {Validation Clause} false-or-sha1-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{sha1-ctx?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} sha1-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-sha1-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{sha1-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hash sha1 api
@subsubsection Context updating functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun sha1-init
Allocate and initialise a new instance of @code{sha1-ctx}; if successful
return the struct, else return @false{}.  @manpage{SHA1_Init, SHA1_Init}
@end defun


@defun sha1-final @var{SHA1}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  @manpage{SHA1_Final,
SHA1_Final}.  It is fine to apply this function multiple times to the
same @var{SHA1} argument.
@end defun


@defun sha1-update @var{SHA1} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{SHA1_Update, SHA1_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash sha1 direct
@subsubsection Directly computing hash checksums


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun sha1 @var{input}
@defunx sha1 @var{input} @var{input.len}
Perform a one--step checksum computing; return a bytevector holding the
result.  @manpage{SHA1, SHA1}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash sha224
@subsection Computing SHA224 hash checksums


@menu
* plain hash sha224 struct::       Hash checksum data structures.
* plain hash sha224 api::          Context updating functions.
* plain hash sha224 direct::       Directly computing hash checksums.
@end menu

@c page
@node plain hash sha224 struct
@subsubsection Hash checksum data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} sha224-ctx
@cindex @var{SHA224} argument
@cindex Argument @var{SHA224}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{SHA224_CTX}; it references an SHA224 hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{SHA224}.

There are two categories of @code{sha224-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{sha224-ctx} instances returned by @func{sha224-init} do own the context.
When instances of this category are garbage collected or when
@func{md5-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun sha224-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{sha224-ctx}; otherwise
return @false{}.
@end defun


@defun sha224-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{sha224-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun sha224-ctx-custom-destructor @var{SHA224}
@defunx set-sha224-ctx-custom-destructor! @var{SHA224} @var{func}
Retrieve or set a destructor function associated to the @var{SHA224}.

Whenever the @var{SHA224} is closed, either explicitly with
@func{sha224-final} or implicitly by the garbage collector, @var{func} is
applied to @var{SHA224} before the internal state of @var{SHA224} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{SHA224}; if we do:

@example
(define context ...)
(set-sha224-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((sha224-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{SHA224}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} sha224-ctx @var{obj}
@deffnx {Validation Clause} false-or-sha224-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{sha224-ctx?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} sha224-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-sha224-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{sha224-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hash sha224 api
@subsubsection Context updating functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun sha224-init
Allocate and initialise a new instance of @code{sha224-ctx}; if successful
return the struct, else return @false{}.  @manpage{SHA224_Init, SHA224_Init}
@end defun


@defun sha224-final @var{SHA224}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  @manpage{SHA224_Final,
SHA224_Final}.  It is fine to apply this function multiple times to the
same @var{SHA224} argument.
@end defun


@defun sha224-update @var{SHA224} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{SHA224_Update, SHA224_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash sha224 direct
@subsubsection Directly computing hash checksums


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun sha224 @var{input}
@defunx sha224 @var{input} @var{input.len}
Perform a one--step checksum computing; return a bytevector holding the
result.  @manpage{SHA224, SHA224}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash sha256
@subsection Computing SHA256 hash checksums


@menu
* plain hash sha256 struct::       Hash checksum data structures.
* plain hash sha256 api::          Context updating functions.
* plain hash sha256 direct::       Directly computing hash checksums.
@end menu

@c page
@node plain hash sha256 struct
@subsubsection Hash checksum data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} sha256-ctx
@cindex @var{SHA256} argument
@cindex Argument @var{SHA256}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{SHA256_CTX}; it references an SHA256 hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{SHA256}.

There are two categories of @code{sha256-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{sha256-ctx} instances returned by @func{sha256-init} do own the context.
When instances of this category are garbage collected or when
@func{md5-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun sha256-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{sha256-ctx}; otherwise
return @false{}.
@end defun


@defun sha256-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{sha256-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun sha256-ctx-custom-destructor @var{SHA256}
@defunx set-sha256-ctx-custom-destructor! @var{SHA256} @var{func}
Retrieve or set a destructor function associated to the @var{SHA256}.

Whenever the @var{SHA256} is closed, either explicitly with
@func{sha256-final} or implicitly by the garbage collector, @var{func} is
applied to @var{SHA256} before the internal state of @var{SHA256} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{SHA256}; if we do:

@example
(define context ...)
(set-sha256-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((sha256-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{SHA256}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} sha256-ctx @var{obj}
@deffnx {Validation Clause} false-or-sha256-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{sha256-ctx?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} sha256-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-sha256-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{sha256-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hash sha256 api
@subsubsection Context updating functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun sha256-init
Allocate and initialise a new instance of @code{sha256-ctx}; if successful
return the struct, else return @false{}.  @manpage{SHA256_Init, SHA256_Init}
@end defun


@defun sha256-final @var{SHA256}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  @manpage{SHA256_Final,
SHA256_Final}.  It is fine to apply this function multiple times to the
same @var{SHA256} argument.
@end defun


@defun sha256-update @var{SHA256} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{SHA256_Update, SHA256_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash sha256 direct
@subsubsection Directly computing hash checksums


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun sha256 @var{input}
@defunx sha256 @var{input} @var{input.len}
Perform a one--step checksum computing; return a bytevector holding the
result.  @manpage{SHA256, SHA256}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash sha384
@subsection Computing SHA384 hash checksums


@menu
* plain hash sha384 struct::       Hash checksum data structures.
* plain hash sha384 api::          Context updating functions.
* plain hash sha384 direct::       Directly computing hash checksums.
@end menu

@c page
@node plain hash sha384 struct
@subsubsection Hash checksum data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} sha384-ctx
@cindex @var{SHA384} argument
@cindex Argument @var{SHA384}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{SHA384_CTX}; it references an SHA384 hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{SHA384}.

There are two categories of @code{sha384-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{sha384-ctx} instances returned by @func{sha384-init} do own the context.
When instances of this category are garbage collected or when
@func{md5-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun sha384-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{sha384-ctx}; otherwise
return @false{}.
@end defun


@defun sha384-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{sha384-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun sha384-ctx-custom-destructor @var{SHA384}
@defunx set-sha384-ctx-custom-destructor! @var{SHA384} @var{func}
Retrieve or set a destructor function associated to the @var{SHA384}.

Whenever the @var{SHA384} is closed, either explicitly with
@func{sha384-final} or implicitly by the garbage collector, @var{func} is
applied to @var{SHA384} before the internal state of @var{SHA384} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{SHA384}; if we do:

@example
(define context ...)
(set-sha384-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((sha384-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{SHA384}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} sha384-ctx @var{obj}
@deffnx {Validation Clause} false-or-sha384-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{sha384-ctx?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} sha384-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-sha384-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{sha384-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hash sha384 api
@subsubsection Context updating functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun sha384-init
Allocate and initialise a new instance of @code{sha384-ctx}; if successful
return the struct, else return @false{}.  @manpage{SHA384_Init, SHA384_Init}
@end defun


@defun sha384-final @var{SHA384}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  @manpage{SHA384_Final,
SHA384_Final}.  It is fine to apply this function multiple times to the
same @var{SHA384} argument.
@end defun


@defun sha384-update @var{SHA384} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{SHA384_Update, SHA384_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash sha384 direct
@subsubsection Directly computing hash checksums


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun sha384 @var{input}
@defunx sha384 @var{input} @var{input.len}
Perform a one--step checksum computing; return a bytevector holding the
result.  @manpage{SHA384, SHA384}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash sha512
@subsection Computing SHA512 hash checksums


@menu
* plain hash sha512 struct::       Hash checksum data structures.
* plain hash sha512 api::          Context updating functions.
* plain hash sha512 direct::       Directly computing hash checksums.
@end menu

@c page
@node plain hash sha512 struct
@subsubsection Hash checksum data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} sha512-ctx
@cindex @var{SHA512} argument
@cindex Argument @var{SHA512}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{SHA512_CTX}; it references an SHA512 hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{SHA512}.

There are two categories of @code{sha512-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{sha512-ctx} instances returned by @func{sha512-init} do own the context.
When instances of this category are garbage collected or when
@func{md5-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun sha512-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{sha512-ctx}; otherwise
return @false{}.
@end defun


@defun sha512-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{sha512-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun sha512-ctx-custom-destructor @var{SHA512}
@defunx set-sha512-ctx-custom-destructor! @var{SHA512} @var{func}
Retrieve or set a destructor function associated to the @var{SHA512}.

Whenever the @var{SHA512} is closed, either explicitly with
@func{sha512-final} or implicitly by the garbage collector, @var{func} is
applied to @var{SHA512} before the internal state of @var{SHA512} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{SHA512}; if we do:

@example
(define context ...)
(set-sha512-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((sha512-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{SHA512}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} sha512-ctx @var{obj}
@deffnx {Validation Clause} false-or-sha512-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{sha512-ctx?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} sha512-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-sha512-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{sha512-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hash sha512 api
@subsubsection Context updating functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun sha512-init
Allocate and initialise a new instance of @code{sha512-ctx}; if successful
return the struct, else return @false{}.  @manpage{SHA512_Init, SHA512_Init}
@end defun


@defun sha512-final @var{SHA512}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  @manpage{SHA512_Final,
SHA512_Final}.  It is fine to apply this function multiple times to the
same @var{SHA512} argument.
@end defun


@defun sha512-update @var{SHA512} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{SHA512_Update, SHA512_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash sha512 direct
@subsubsection Directly computing hash checksums


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun sha512 @var{input}
@defunx sha512 @var{input} @var{input.len}
Perform a one--step checksum computing; return a bytevector holding the
result.  @manpage{SHA512, SHA512}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash ripemd160
@subsection Computing RIPEMD160 hash checksums


@menu
* plain hash ripemd160 struct::       Hash checksum data structures.
* plain hash ripemd160 api::          Context updating functions.
* plain hash ripemd160 direct::       Directly computing hash checksums.
@end menu

@c page
@node plain hash ripemd160 struct
@subsubsection Hash checksum data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} ripemd160-ctx
@cindex @var{RIPEMD160} argument
@cindex Argument @var{RIPEMD160}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{RIPEMD160_CTX}; it references an RIPEMD160 hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{RIPEMD160}.

There are two categories of @code{ripemd160-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{ripemd160-ctx} instances returned by @func{ripemd160-init} do own the context.
When instances of this category are garbage collected or when
@func{md5-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun ripemd160-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{ripemd160-ctx}; otherwise
return @false{}.
@end defun


@defun ripemd160-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{ripemd160-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun ripemd160-ctx-custom-destructor @var{RIPEMD160}
@defunx set-ripemd160-ctx-custom-destructor! @var{RIPEMD160} @var{func}
Retrieve or set a destructor function associated to the @var{RIPEMD160}.

Whenever the @var{RIPEMD160} is closed, either explicitly with
@func{ripemd160-final} or implicitly by the garbage collector, @var{func} is
applied to @var{RIPEMD160} before the internal state of @var{RIPEMD160} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{RIPEMD160}; if we do:

@example
(define context ...)
(set-ripemd160-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((ripemd160-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{RIPEMD160}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} ripemd160-ctx @var{obj}
@deffnx {Validation Clause} false-or-ripemd160-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{ripemd160-ctx?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} ripemd160-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-ripemd160-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{ripemd160-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hash ripemd160 api
@subsubsection Context updating functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun ripemd160-init
Allocate and initialise a new instance of @code{ripemd160-ctx}; if successful
return the struct, else return @false{}.  @manpage{RIPEMD160_Init, RIPEMD160_Init}
@end defun


@defun ripemd160-final @var{RIPEMD160}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  @manpage{RIPEMD160_Final,
RIPEMD160_Final}.  It is fine to apply this function multiple times to the
same @var{RIPEMD160} argument.
@end defun


@defun ripemd160-update @var{RIPEMD160} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{RIPEMD160_Update, RIPEMD160_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash ripemd160 direct
@subsubsection Directly computing hash checksums


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun ripemd160 @var{input}
@defunx ripemd160 @var{input} @var{input.len}
Perform a one--step checksum computing; return a bytevector holding the
result.  @manpage{RIPEMD160, RIPEMD160}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash whirlpool
@subsection Computing WHIRLPOOL hash checksums


@menu
* plain hash whirlpool struct::       Hash checksum data structures.
* plain hash whirlpool api::          Context updating functions.
* plain hash whirlpool direct::       Directly computing hash checksums.
@end menu

@c page
@node plain hash whirlpool struct
@subsubsection Hash checksum data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} whirlpool-ctx
@cindex @var{WHIRLPOOL} argument
@cindex Argument @var{WHIRLPOOL}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{WHIRLPOOL_CTX}; it references an WHIRLPOOL hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{WHIRLPOOL}.

There are two categories of @code{whirlpool-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{whirlpool-ctx} instances returned by @func{whirlpool-init} do own the context.
When instances of this category are garbage collected or when
@func{whirlpool-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun whirlpool-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{whirlpool-ctx}; otherwise
return @false{}.
@end defun


@defun whirlpool-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{whirlpool-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun whirlpool-ctx-custom-destructor @var{WHIRLPOOL}
@defunx set-whirlpool-ctx-custom-destructor! @var{WHIRLPOOL} @var{func}
Retrieve or set a destructor function associated to the @var{WHIRLPOOL}.

Whenever the @var{WHIRLPOOL} is closed, either explicitly with
@func{whirlpool-final} or implicitly by the garbage collector, @var{func} is
applied to @var{WHIRLPOOL} before the internal state of @var{WHIRLPOOL} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{WHIRLPOOL}; if we do:

@example
(define context ...)
(set-whirlpool-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((whirlpool-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{WHIRLPOOL}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} whirlpool-ctx @var{obj}
@deffnx {Validation Clause} false-or-whirlpool-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{whirlpool-ctx?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} whirlpool-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-whirlpool-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{whirlpool-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hash whirlpool api
@subsubsection Context updating functions


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun whirlpool-init
Allocate and initialise a new instance of @code{whirlpool-ctx}; if successful
return the struct, else return @false{}.  @manpage{WHIRLPOOL_Init, WHIRLPOOL_Init}
@end defun


@defun whirlpool-final @var{WHIRLPOOL}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  @manpage{WHIRLPOOL_Final,
WHIRLPOOL_Final}.  It is fine to apply this function multiple times to the
same @var{WHIRLPOOL} argument.
@end defun


@defun whirlpool-update @var{WHIRLPOOL} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{WHIRLPOOL_Update, WHIRLPOOL_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hash whirlpool direct
@subsubsection Directly computing hash checksums


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun whirlpool @var{input}
@defunx whirlpool @var{input} @var{input.len}
Perform a one--step checksum computing; return a bytevector holding the
result.  @manpage{WHIRLPOOL, WHIRLPOOL}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain hmac
@section Computing message authentication codes


@menu
* plain hmac struct::           HMAC data structures.
* plain hmac api::              Context updating functions.
* plain hmac direct::           Directly computing HMACs.
@end menu

@c page
@node plain hmac struct
@subsection HMAC data structures


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} hmac-ctx
@cindex @var{HMAC} argument
@cindex Argument @var{HMAC}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{HMAC_CTX}; it references an HMAC hash checksum
context.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{HMAC}.

There are two categories of @code{hmac-ctx} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{hmac-ctx} instances returned by @func{hmac-init} do own the
context.  When instances of this category are garbage collected or when
@func{hmac-final} is applied to them: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun hmac-ctx? @var{obj}
Return @true{} if @var{obj} is an instance of @code{hmac-ctx}; otherwise
return @false{}.
@end defun


@defun hmac-ctx?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{hmac-ctx} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun hmac-ctx-custom-destructor @var{HMAC}
@defunx set-hmac-ctx-custom-destructor! @var{HMAC} @var{func}
Retrieve or set a destructor function associated to the @var{HMAC}.

Whenever the @var{HMAC} is closed, either explicitly with
@func{hmac-final} or implicitly by the garbage collector, @var{func} is
applied to @var{HMAC} before the internal state of @var{HMAC} is
finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{HMAC}; if we do:

@example
(define context ...)
(set-hmac-ctx-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((hmac-ctx-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{HMAC}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} hmac-ctx @var{obj}
@deffnx {Validation Clause} false-or-hmac-ctx @var{obj}
Succeed if @var{obj} satisfies the predicate @func{hmac-ctx?}; the
second clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} hmac-ctx/alive @var{obj}
@deffnx {Validation Clause} false-or-hmac-ctx/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{hmac-ctx?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain hmac api
@subsection Context updating functions


Usage example:

@example
#!r6rs
(import (vicare)
  (prefix (vicare crypto openssl) ssl.))

(let ((ctx (ssl.hmac-init "key" 'md5)))
  (ssl.hmac-update ctx "ciao")
  (ssl.hmac-final ctx))
@result{} #vu8(104 95 146 126 133 66
   104 215 19 225 230 101 126 75 39 188)
@end example

The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun hmac-init @var{key} @var{md}
@defunx hmac-init @var{key} @var{key.len} @var{md}
Allocate and initialise a new instance of @code{hmac-ctx}; if successful
return the struct, else return @false{}.  Notice that this Scheme
function performs the work of both @cfunc{HMAC_CTX_init} and
@cfunc{HMAC_Init}.  @manpage{HMAC_Init, HMAC_Init}.

@var{key} must be a generalised C string, @vicareref{cbuffers strings,
Introduction to generalised C strings}.  When @var{key} is a string: it
is converted to a bytevector with @func{string->utf8}.

The optional @var{key.len} must be @false{} or an exact integer in the
range of the C language type @code{size_t}.  When @var{key} is a pointer
object: @var{key.len} must represent the number of bytes available in
the referenced memory block; otherwise @var{key.len} is ignored.

@var{md} must be a symbol among:

@example
md4             md5             mdc2
sha1            sha224          sha256
sha384          sha512          ripemd160
whirlpool       dss             dss1
@end example
@end defun


@defun hmac-final @var{HMAC}
Finalise a checksum context; if successful return a bytevector holding
the computed checksum, else return @false{}.  Notice that this Scheme
function performs the work of both @cfunc{HMAC_CTX_cleaup} and
@cfunc{HMAC_Final}.  @manpage{HMAC_Final, HMAC_Final}.  It is fine to
apply this function multiple times to the same @var{HMAC} argument.
@end defun


@defun hmac-update @var{HMAC} @var{input} @var{input.len}
Update the checksum context with the given input data.
@manpage{HMAC_Update, HMAC_Update}

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun


@defun hmac-ctx-copy @var{DST-HMAC} @var{SRC-HMAC}
Duplicate an HMAC context from @var{SRC-HMAC} to @var{DST-HMAC}; if
successful return true, else return @false{}.  @manpage{HMAC_CTX_copy,
HMAC_CTX_copy}.
@end defun


@defun hmac-ctx-set-flags @var{HMAC} @var{flags}
Set flags in an HMAC context; return unspecified values.
@manpage{HMAC_CTX_copy}.
@end defun

@c page
@node plain hmac direct
@subsection Directly computing HMACs


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun hmac @var{md} @var{key} @var{key.len} @var{input} @var{input.len}
Perform a one--step HMAC computing; return a bytevector holding the
result, or @false{} if an error occurs.  @manpage{HMAC, HMAC}.

@var{md} must be a symbol among:

@example
md4             md5             mdc2
sha1            sha224          sha256
sha384          sha512          ripemd160
whirlpool       dss             dss1
@end example

@var{key} and @var{key.len} must represent a generalised C string,
@cstringsref{}.  When @var{key} is a string: it is converted to a
bytevector with @func{string->utf8}.

@var{input} and @var{input.len} must represent a generalised C string,
@cstringsref{}.  When @var{input} is a string: it is converted to a
bytevector with @func{string->utf8}.
@end defun

@c page
@node plain crypto
@section Low--level cryptographic algorithms.


@menu
* plain crypto aes::            The AES algorithm.
@end menu

@c page
@node plain crypto aes
@subsection The AES algorithm


The cryptographic algorithm AES operates on blocks of size @math{16}.

@menu
* plain crypto aes struct::     Context data structure.
* plain crypto aes key::        Selecting the key.
* plain crypto aes crypt::      Encryption and decryption.
* plain crypto aes misc::       Miscellaneous functions and syntaxes.
@end menu

@c page
@node plain crypto aes struct
@subsubsection Context data structure


The following bindings are exported by the library @library{vicare
crypto openssl}.


@deftp {Struct Type} aes-key
@cindex @var{AES} argument
@cindex Argument @var{AES}
An opaque Scheme structure holding a pointer object referencing the C
language type @code{AES_KEY}; it references an AES encryption or
decryption key.

When instances of this type are used as arguments to functions: this
documentation identifies them as @var{AES}.

There are two categories of @code{aes-key} instances: those who own the
underlying checksum context and those who merely reference it.

@itemize
@item
@code{aes-key} instances returned by @func{aes-set-encrypt-key} and
@func{aes-set-decrypt-key} do own the context.  When instances of this
category are garbage collected: the context is closed, all the
associated data is finalised; any error is ignored in this procedure.
@end itemize
@end deftp


@defun aes-key? @var{obj}
Return @true{} if @var{obj} is an instance of @code{aes-key}; otherwise
return @false{}.
@end defun


@defun aes-key?/alive @var{obj}
Return @true{} if @var{obj} is an instance of @code{aes-key} and the
context it represents is open; otherwise return @false{}.
@end defun


@defun aes-key-custom-destructor @var{AES}
@defunx set-aes-key-custom-destructor! @var{AES} @var{func}
Retrieve or set a destructor function associated to the @var{AES}.

Whenever the @var{AES} is closed: @var{func} is applied to @var{AES}
before the internal state of @var{AES} is finalised.

Notice that @var{func} can do anything, not only destroy some state
associated to @var{AES}; if we do:

@example
(define context ...)
(set-aes-key-custom-destructor! context
  (let ((state (make-some-data-struct)))
    (case-lambda
      ((sex)
       (destroy state))
      (()
       state))))

(let ((state ((aes-key-custom-destructor context))))
  (do-something-with context state))
@end example

@noindent
we can easily associate values to @var{AES}.
@end defun

@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} aes-key @var{obj}
@deffnx {Validation Clause} false-or-aes-key @var{obj}
Succeed if @var{obj} satisfies the predicate @func{aes-key?}; the second
clause also accepts @false{}.
@end deffn


@deffn {Validation Clause} aes-key/alive @var{obj}
@deffnx {Validation Clause} false-or-aes-key/alive @var{obj}
Succeed if @var{obj} satisfies the predicate @func{aes-key?/alive}; the
second clause also accepts @false{}.
@end deffn

@c page
@node plain crypto aes key
@subsubsection Selecting the key


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun aes-set-encrypt-key @var{key}
@defunx aes-set-encrypt-key @var{key} @var{key.len}
Build an instance of @code{aes-ctx} initialised with the encryption
@var{key} and configured with @var{bits}; if successful return the
struct, else return @false{}.

@var{key} and @var{key.len} must represent a generalised C string,
@cstringsref{}.  When @var{key} is a string: it is converted to a
bytevector with @func{string->ascii}.  The key length, measured in
bytes, must be: @math{16}, @math{24} or @math{32}; corresponding to a
length measured in bits of: @math{128}, @math{192}, @math{256}.
@end defun


@defun aes-set-decrypt-key @var{key}
@defunx aes-set-decrypt-key @var{key} @var{key.len}
Build an instance of @code{aes-ctx} initialised with the decryption
@var{key} and configured with @var{bits}; if successful return the
struct, else return @false{}.

@var{key} and @var{key.len} must represent a generalised C string,
@cstringsref{}.  When @var{key} is a string: it is converted to a
bytevector with @func{string->ascii}.  The key length, measured in
bytes, must be: @math{16}, @math{24} or @math{32}; corresponding to a
length measured in bits of: @math{128}, @math{192}, @math{256}.
@end defun

@c page
@node plain crypto aes crypt
@subsubsection Encryption and decryption


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun aes-encrypt @var{in} @var{in.len} @var{ou} @var{ou.len} @var{AES}
@defunx aes-decrypt @var{in} @var{in.len} @var{ou} @var{ou.len} @var{AES}
Encrypt or decrypt the single data block @var{in} and store the result
in @var{ou}; return unspecified values.

@var{in}, @var{in.len} and @var{ou}, @var{ou.len} must represent
generalised C buffers, @cbuffersref{}.  Their length must be equal to
@code{AES_BLOCK_SIZE} (@math{16}).  @var{in} and @var{ou} can overlap
and also be the same argument.

@example
#!r6rs
(import (vicare)
  (prefix (vicare crypto openssl) ssl.)
  (prefix (vicare crypto openssl constants) ssl.)

(define key.en (ssl.aes-set-encrypt-key "0123456789012345"))
(define key.de (ssl.aes-set-decrypt-key "0123456789012345"))

(define data.in (make-bytevector ssl.AES_BLOCK_SIZE 123))
(define data.en (make-bytevector ssl.AES_BLOCK_SIZE 0))
(define data.de (make-bytevector ssl.AES_BLOCK_SIZE 0))

(ssl.aes-encrypt data.in #f data.en #f key.en)
(ssl.aes-decrypt data.en #f data.de #f key.de)

data.in @result{} #vu8(123 123 123 123 123 123
   123 123 123 123 123 123 123 123 123 123)

data.en @result{} #vu8(204 84 141 21 154 178 104
   243 186 57 101 209 29 113 127 2)

data.de @result{} #vu8(123 123 123 123 123 123
   123 123 123 123 123 123 123 123 123 123)
@end example
@end defun


@defun aes-ecb-encrypt @var{in} @var{in.len} @var{ou} @var{ou.len} @var{AES}
@defunx aes-ecb-decrypt @var{in} @var{in.len} @var{ou} @var{ou.len} @var{AES}
Encrypt or decrypt the single data block @var{in}, using the ECB scheme,
and store the result in @var{ou}; return unspecified values.

@var{in}, @var{in.len} and @var{ou}, @var{ou.len} must represent
generalised C buffers, @cbuffersref{}.  Their length must be equal to
@code{AES_BLOCK_SIZE} (@math{16}).  @var{in} and @var{ou} can overlap
and also be the same argument.

@example
#!r6rs
(import (vicare)
  (prefix (vicare crypto openssl) ssl.)
  (prefix (vicare crypto openssl constants) ssl.)

(define key.en (ssl.aes-set-encrypt-key "0123456789012345"))
(define key.de (ssl.aes-set-decrypt-key "0123456789012345"))

(define data.in (make-bytevector ssl.AES_BLOCK_SIZE 123))
(define data.en (make-bytevector ssl.AES_BLOCK_SIZE 0))
(define data.de (make-bytevector ssl.AES_BLOCK_SIZE 0))

(ssl.aes-ecb-encrypt data.in #f data.en #f key.en)
(ssl.aes-ecb-decrypt data.en #f data.de #f key.de)
@end example
@end defun


@defun aes-cbc-encrypt @var{in} @var{in.len} @var{ou} @var{ou.len} @var{AES} @var{iv} @var{iv.len}
@defunx aes-cbc-decrypt @var{in} @var{in.len} @var{ou} @var{ou.len} @var{AES} @var{iv} @var{iv.len}
Encrypt or decrypt multiple data blocks @var{in}, using the CBC scheme,
and store the result in @var{ou}; return unspecified values.

@var{in}, @var{in.len} and @var{ou}, @var{ou.len} must represent
generalised C buffers, @cbuffersref{}.  Their length must be an exact
multiple of @code{AES_BLOCK_SIZE} (@math{16}).  @var{in} and @var{ou}
can overlap and also be the same argument.

@var{iv} and @var{iv.len} must represent a generalised C buffer holding
the initialisation vector, @cbuffersref{}.  Its length must be equal to
@code{AES_BLOCK_SIZE}.

@example
#!r6rs
(import (vicare)
  (prefix (vicare crypto openssl) ssl.)
  (prefix (vicare crypto openssl constants) ssl.)

(define key.en (ssl.aes-set-encrypt-key "0123456789012345"))
(define key.de (ssl.aes-set-decrypt-key "0123456789012345"))

(define iv (make-bytevector ssl.AES_BLOCK_SIZE 99))

(define data.len (* 5 ssl.AES_BLOCK_SIZE))
(define data.in (make-bytevector data.len 123))
(define data.en (make-bytevector data.len 0))
(define data.de (make-bytevector data.len 0))

(ssl.aes-cbc-encrypt data.in #f data.en #f key.en iv #f)
(ssl.aes-cbc-decrypt data.en #f data.de #f key.de iv #f)
@end example
@end defun


@c page
@node plain crypto aes misc
@subsubsection Miscellaneous functions and syntaxes


The following bindings are exported by the library @library{vicare
crypto openssl}.


@defun aes-options
If successful return a string representing some kind of options,
otherwise raise an @condition{error} condition.
@end defun


@defun aes-block-len? @var{obj}
Return @true{} if @var{obj} is a fixnum equal to the AES block size;
otherwise return @false{}.
@end defun


@defun aes-data-len? @var{obj}
Return @true{} if @var{obj} is a fixnum equal to an exact multiple of
the AES block size; otherwise return @false{}.
@end defun


@defun aes-key-len? @var{obj}
Return @true{} if @var{obj} is a fixnum representing a valid AES key
length; valid values are: @math{16}, @math{24}, @math{32}.  Otherwise
return @false{}.
@end defun


@c ------------------------------------------------------------

@subsubheading Arguments validation

The following bindings are meant to be used along the library
@library{vicare arguments validation}.


@deffn {Validation Clause} aes-block-len @var{buf} @var{buf.len}
@var{buf} and @var{buf.len} must represent a generalised C buffer,
@cbuffersref{}.  Succeed if the length of the buffer equals the AES
block size.
@end deffn


@deffn {Validation Clause} aes-data-len @var{buf} @var{buf.len}
@var{buf} and @var{buf.len} must represent a generalised C buffer,
@cbuffersref{}.  Succeed if the length of the buffer is an exact
multiple of the AES block size.
@end deffn


@deffn {Validation Clause} aes-key-len @var{obj}
Succeed if @var{obj} is a finxum representing a valid AES key length;
valid values are: @math{16}, @math{24}, @math{32}.
@end deffn

@c page
@node plain evp
@section High--level cryptographic functions


@menu
* plain evp hash::              High-level hash functions.
@end menu

@c page
@node plain evp hash
@subsection High--level hash functions




@c page
@c ------------------------------------------------------------
@c Appendices.
@c ------------------------------------------------------------

@include gpl-3.0.texi
@include fdl-1.3.texi

@c page
@node references
@appendix Bibliography and references


The documentation of @value{PACKAGE} is available online:

@center @value{DOCUMENTATION_URL}

@noindent
the latest version of this package can be downloaded from:

@center @value{DOWNLOAD_URL}

@noindent
development takes place at:

@center @value{GITHUB_URL}

@noindent
the home page of the Vicare project is at:

@center @url{http://marcomaggi.github.com/vicare.html}

@noindent
the home page of the Nausicaa project is at:

@center @url{http://marcomaggi.github.com/nausicaa.html}

@noindent
@value{FOREIGN_PACKAGE} can be found here:

@center @value{FOREIGN_URL}

@c page
@node concept index
@appendix An entry for each concept

@printindex cp

@node function index
@appendix An entry for each function.

@printindex fn

@node variable index
@appendix An entry for each variable.

@printindex vr

@node type index
@appendix An entry for each type.

@printindex tp

@contents
@bye

@c end of file

